apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-deploy-public
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chandramohan97911/podinfo-deploy.git #git@github.com:chandramohan97911/podinfo-deploy.git
    targetRevision: HEAD
    path: ./
  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true